apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 522814735019.dkr.ecr.us-east-1.amazonaws.com/pavanspring@sha256:92d616987ab84d0364eecd01183da6b3a088cb1941d6030ff96e870fa0733767
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "/api/tasks"
        ports:
        - containerPort: 3000
