apiVersion: v1
kind: Service
metadata: 
  name: frontend
  namespace: three-tier
spec:
  type: LoadBalancer
  selector:
    role: frontend
  ports:
    - port: 80            # Port exposed externally
      targetPort: 3000    # Port on the container
      protocol: TCP
